# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
# For a list of all available actions, check out https://docs.fastlane.tools/actions
# For a list of all available plugins, check out https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


private_lane :increment_package_version do
  package = read_json(json_path: "./package.json")
  root_package = read_json(json_path: "../web/package.json")

  UI.message("Updating from version #{package[:version]} to #{root_package[:version]}")
  package[:version] = root_package[:version]

  write_json(
    hash: package,
    file_path: "./package.json"
  )

  package[:version]
end

platform :ios do
  ios_dir = File.expand_path('../ios')

  lane :bump_version do
    version = increment_package_version
    increment_version_number_in_xcodeproj(
      xcodeproj: File.join(ios_dir,'App/App.xcodeproj'),
      version_number: version
    )
    increment_build_number_in_xcodeproj(
      xcodeproj: File.join(ios_dir,'App/App.xcodeproj'),
      build_number: version
    )
  end


  # See README for guide on how to set this up
  desc "Submit a new Beta build"
  lane :beta do
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      ignore_files: ['mobileapp/fastlane/Fastfile']
    )
    bump_version
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(
        workspace: File.join(ios_dir,'App/App.xcworkspace'),
      )
    upload_to_testflight()
    reset_git_repo(
      files: [
        File.join(ios_dir,'App/App.xcodeproj/project.pbxproj'),
        './package.json'
      ]
    )
    #slack(message: 'A new build is ready to be tested! Please open TestFlight and update the app.')

  end

end

platform :android do
  android_dir = File.expand_path('../android')

  lane :bump_version do
    version = increment_package_version
    increment_version_code(
      gradle_file_path: File.join(android_dir,"app/build.gradle"),
    )
    increment_version_name(
      gradle_file_path: File.join(android_dir,"app/build.gradle"),
      version_name: version
    )
  end

  # See README for guide on how to set this up
  desc "Submit a new Beta build"
  lane :beta do
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      ignore_files: ['mobileapp/fastlane/Fastfile']
    )
    bump_version
    gradle(task: 'bundle',build_type: 'Release', project_dir: android_dir)
    upload_to_play_store(
      track: 'internal',
      aab: File.join(android_dir,"app/build/outputs/bundle/release/app-release.aab"),
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    reset_git_repo(
      files: [
        File.join(android_dir,'app/build.gradle'),
        './package.json'
      ]
    )
    #slack(message: 'A new build is ready to be tested! Please open Play Store and update the app.')
  end
end
