# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
# For a list of all available actions, check out https://docs.fastlane.tools/actions
# For a list of all available plugins, check out https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

package = load_json(json_path: "./package.json")
package_version = package["version"]

platform :ios do
  ios_dir = File.expand_path('../ios')

  lane :bump_version do
    increment_build_number(
      xcodeproj: File.join(android_dir,'App/App.xcodeproj')
    )
    increment_version_number(
      xcodeproj: File.join(android_dir,'App/App.xcodeproj'),
      version_number: package['version']
    )
  end


  desc "Submit a new Beta build"
  lane :beta do
    # ensure_git_status_clean
    # bump_version
    # build
    # upload_to_testflight
    # reset_git_repo
    # revert bump?
  end

end

platform :android do
  android_dir = File.expand_path('../android')

  lane :bump_version do
    increment_version_code(
      gradle_file_path: File.join(android_dir,"app/build.gradle"),
    )
    increment_version_name(
      gradle_file_path: File.join(android_dir,"app/build.gradle"),
      version_name: package['version']
    )
  end

  desc "Submit a new Beta build"
  lane :beta do
    # ensure_git_status_clean
    bump_version
    gradle(task: 'bundle',build_type: 'Release', project_dir: android_dir)
    upload_to_play_store(track: 'internal')
    #slack(message: 'Successfully distributed a new beta build')
    # reset_git_repo
  end
end
