lonlat:
  - 15.486554
  - 48.909846
parsers:
  exchange: CZ.fetch_exchange
  shadowAuctionAtcDayAhead: JAO.fetch_shadow_auction_atc_day_ahead
  maxBexDayAhead: JAO.fetch_core_max_bex_day_ahead
  scheduledExchangesDayAhead: JAO.fetch_core_scheduled_exchanges_day_ahead
  scheduledExchangesTotal: ENTSOE.fetch_scheduled_exchanges_total
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
