lonlat:
  - 15.486554
  - 48.909846
parsers:
  exchange: CZ.fetch_exchange
  exchangeShadowAuctionAtcDayAhead: JAO.fetch_shadow_auction_atc_day_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
