lonlat:
  - 15.486554
  - 48.909846
parsers:
  exchange: CZ.fetch_exchange
  shadowAuctionAtc: JAO.fetch_shadow_auction_atc
  maxExchanges: JAO.fetch_core_max_exchanges
  scheduledExchanges: JAO.fetch_core_scheduled_exchanges
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
