capacity:
  - -1000
  - 1000
lonlat:
  - 6.4
  - 50.4
parsers:
  exchange: ENTSOE.fetch_exchange
  exchangeCapacityForecastDayAhead: ENTSOE.fetch_exchange_capacity_forecasts_day_ahead
  exchangeCapacityForecastWeekAhead: ENTSOE.fetch_exchange_capacity_forecasts_week_ahead
  exchangeCapacityForecastMonthAhead: ENTSOE.fetch_exchange_capacity_forecasts_month_ahead
  exchangeShadowAuctionAtcDayAhead: JAO.fetch_shadow_auction_atc_day_ahead
  exchangeMaxExchangesDayAhead: JAO.fetch_core_max_exchanges_day_ahead
  exchangeScheduledExchangesDayAhead: JAO.fetch_core_scheduled_exchanges_day_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 90
