capacity:
  - -2485
  - 2485
lonlat:
  - 26.89864
  - 42.002181
parsers:
  exchange: ENTSOE.fetch_exchange
  exchangeCapacityForecastDayAhead: ENTSOE.fetch_exchange_capacity_forecasts_day_ahead
  exchangeCapacityForecastWeekAhead: ENTSOE.fetch_exchange_capacity_forecasts_week_ahead
  exchangeCapacityForecastMonthAhead: ENTSOE.fetch_exchange_capacity_forecasts_month_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 135
