lonlat:
  - 16.496641
  - 50.269487
parsers:
  exchange: CZ.fetch_exchange
  shadowAuctionAtc: JAO.fetch_shadow_auction_atc
  maxExchanges: JAO.fetch_core_max_exchanges
  scheduledExchanges: JAO.fetch_core_scheduled_exchanges
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 45
