capacity:
  - -985
  - 1000
lonlat:
  - 12.135031
  - 54.486043
parsers:
  exchange: DK.fetch_exchange
  maxExchanges: JAO.fetch_nordic_max_exchanges
  scheduledExchanges: JAO.fetch_core_scheduled_exchanges
  maxBorderFlow: JAO.fetch_nordic_max_border_flow
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
