capacity:
  - -2500
  - 2500
lonlat:
  - 9.3
  - 54.9
parsers:
  exchange: DK.fetch_exchange
  exchangeCoreExternalAtcDayAhead: JAO.fetch_core_external_atc_day_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
