capacity:
  - -2500
  - 2500
lonlat:
  - 9.3
  - 54.9
parsers:
  exchange: DK.fetch_exchange
  coreExternalAtc: JAO.fetch_core_external_atc
  maxExchanges: JAO.fetch_nordic_max_exchanges
  scheduledExchanges: JAO.fetch_core_scheduled_exchanges
  maxBorderFlow: JAO.fetch_nordic_max_border_flow
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
