_comment: 700MW from COBRAcable https://en.wikipedia.org/wiki/COBRAcable
capacity:
  - -700
  - 700
lonlat:
  - 7.4
  - 54.5
parsers:
  exchange: DK.fetch_exchange
  coreExternalAtc: JAO.fetch_core_external_atc
  maxExchanges: JAO.fetch_nordic_max_exchanges
  scheduledExchanges: JAO.fetch_core_scheduled_exchanges
  maxBorderFlow: JAO.fetch_nordic_max_border_flow
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: -150
