capacity:
  - -600
  - 590
lonlat:
  - 10.948508
  - 55.407235
parsers:
  exchange: DK.fetch_exchange
  exchangeCapacityForecastDayAhead: ENTSOE.fetch_exchange_capacity_forecasts_day_ahead
  exchangeCapacityForecastWeekAhead: ENTSOE.fetch_exchange_capacity_forecasts_week_ahead
  exchangeCapacityForecastMonthAhead: ENTSOE.fetch_exchange_capacity_forecasts_month_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 90
