capacity:
  - -1632
  - 1632
lonlat:
  - 8.8
  - 57.7
parsers:
  exchange: DK.fetch_exchange
  exchangeMaxExchangesDayAhead: JAO.fetch_nordic_max_exchanges_day_ahead
  exchangeMaxBorderFlowDayAhead: JAO.fetch_nordic_max_border_flow_day_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: -25
