capacity:
  - -1000
  - 1000
lonlat:
  - -5.7
  - 53
parsers:
  exchange: ELEXON.fetch_exchange
  scheduledExchangesDayAhead: ENTSOE.fetch_scheduled_exchanges_day_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: -80
