capacity:
  - -1632
  - 1632
lonlat:
  - 22.011736
  - 41.160374
parsers:
  exchange: ENTSOE.fetch_exchange
  exchangeCapacityForecastDayAhead: ENTSOE.fetch_exchange_capacity_forecasts_day_ahead
  exchangeCapacityForecastWeekAhead: ENTSOE.fetch_exchange_capacity_forecasts_week_ahead
  exchangeCapacityForecastMonthAhead: ENTSOE.fetch_exchange_capacity_forecasts_month_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
