lonlat:
  - 19.615617
  - 48.204006
parsers:
  exchange: ENTSOE.fetch_exchange
  exchangeCapacityForecastDayAhead: ENTSOE.fetch_exchange_capacity_forecasts_day_ahead
  exchangeCapacityForecastWeekAhead: ENTSOE.fetch_exchange_capacity_forecasts_week_ahead
  exchangeCapacityForecastMonthAhead: ENTSOE.fetch_exchange_capacity_forecasts_month_ahead
  shadowAuctionAtc: JAO.fetch_shadow_auction_atc
  maxExchanges: JAO.fetch_core_max_exchanges
  scheduledExchanges: JAO.fetch_core_scheduled_exchanges
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 0
