capacity:
  - -600
  - 600
lonlat:
  - 15.969256
  - 55.215172
parsers:
  exchange: ENTSOE.fetch_exchange
  exchangeCapacityForecastDayAhead: ENTSOE.fetch_exchange_capacity_forecasts_day_ahead
  exchangeCapacityForecastWeekAhead: ENTSOE.fetch_exchange_capacity_forecasts_week_ahead
  exchangeCapacityForecastMonthAhead: ENTSOE.fetch_exchange_capacity_forecasts_month_ahead
  maxBexDayAhead: JAO.fetch_nordic_max_bex_day_ahead
  scheduledExchangesDayAhead: ENTSOE.fetch_scheduled_exchanges_day_ahead
  scheduledExchangesTotal: ENTSOE.fetch_scheduled_exchanges_total
  maxBflowDayAhead: JAO.fetch_nordic_max_bflow_day_ahead
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: -20
