"""Constants for CR parser."""

TIMEZONE = 'America/Costa_Rica'
DATE_FORMAT = 'DD/MM/YYYY'
POWER_PLANTS = {
    'Aeroenergía': 'wind',
    'Altamira': 'wind',
    'Angostura': 'hydro',
    'Arenal': 'hydro',
    'Balsa Inferior': 'hydro',
    'Barranca': 'oil',
    'Barro Morado': 'geothermal',
    'Bijagua': 'hydro',
    'Birris12': 'hydro',
    'Birris3': 'hydro',
    'Boca de Pozo': 'hydro',
    'CNFL': 'hydro',
    'Cachí': 'hydro',
    'Campos Azules': 'wind',
    'Canalete': 'hydro',
    'Cariblanco': 'hydro',
    'Carrillos': 'hydro',
    'Caño Grande': 'hydro',
    'Caño Grande III': 'hydro',
    'Chiripa': 'wind',
    'Chocosuelas': 'hydro',
    'Chucás': 'hydro',
    'Cubujuquí': 'hydro',
    'Daniel Gutiérrez': 'hydro',
    'Dengo': 'hydro',
    'Don Pedro': 'hydro',
    'Doña Julia': 'hydro',
    'Echandi': 'hydro',
    'El Angel': 'hydro',
    'El Angel Ampliación': 'hydro',
    'El Embalse': 'hydro',
    'El General': 'hydro',
    'El Viejo': 'biomass',
    'Garabito': 'oil',
    'Garita': 'hydro',
    'Guápiles': 'oil',
    'Hidrozarcas': 'hydro',
    'Jorge Manuel Dengo': 'hydro',
    'La Esperanza (CoopeL)': 'hydro',
    'La Joya': 'hydro',
    'Las Pailas II': 'geothermal',
    'Los Negros': 'hydro',
    'Los Negros II': 'hydro',
    'Los Santos': 'wind',
    'MOVASA': 'wind',
    'Matamoros': 'hydro',
    'Miravalles I': 'geothermal',
    'Miravalles II': 'geothermal',
    'Miravalles III': 'geothermal',
    'Miravalles V': 'geothermal',
    'Moín I': 'oil',
    'Moín II': 'oil',
    'Moín III': 'oil',
    'Orosí': 'wind',
    'Orotina': 'unknown',
    'Otros': 'unknown',
    'PE Cacao': 'wind',
    'PE Mogote': 'wind',
    'PE Río Naranjo': 'hydro',
    'PEG': 'wind',
    'Pailas': 'geothermal',
    'Parque Solar Juanilama': 'solar',
    'Parque Solar Miravalles': 'solar',
    'Peñas Blancas': 'hydro',
    'Pirrís': 'hydro',
    'Plantas Eólicas': 'wind',
    'Platanar': 'hydro',
    'Pocosol': 'hydro',
    'Poás I y II': 'hydro',
    'Reventazón': 'hydro',
    'Río Lajas': 'hydro',
    'Río Macho': 'hydro',
    'San Antonio': 'oil',
    'San Lorenzo (C)': 'hydro',
    'Sandillal': 'hydro',
    'Suerkata': 'hydro',
    'Taboga': 'biomass',
    'Tacares': 'hydro',
    'Tejona': 'wind',
    'Tilawind': 'wind',
    'Torito': 'hydro',
    'Toro I': 'hydro',
    'Toro II': 'hydro',
    'Toro III': 'hydro',
    'Tuis (JASEC)': 'hydro',
    'Valle Central': 'wind',
    'Vara Blanca': 'hydro',
    'Ventanas-Garita': 'hydro',
    'Vientos de La Perla': 'wind',
    'Vientos de Miramar': 'wind',
    'Vientos del Este': 'wind',
    'Volcán': 'hydro',
}

CHARACTERISTIC_NAME = 'Angostura'
