# snapshottest: v1 - https://goo.gl/zC4yUc

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["test_fetch_exchange_live[AM] 1"] = [
    {
        "datetime": "2024-04-08T12:00:00+00:00",
        "netFlow": 0.0,
        "sortedZoneKeys": "AM->GE",
        "source": "gse.com.ge",
        "sourceType": "measured",
    }
]

snapshots["test_fetch_exchange_live[AZ] 1"] = [
    {
        "datetime": "2024-04-08T12:00:00+00:00",
        "netFlow": -20.295879,
        "sortedZoneKeys": "AZ->GE",
        "source": "gse.com.ge",
        "sourceType": "measured",
    }
]

snapshots["test_fetch_exchange_live[RU-1] 1"] = [
    {
        "datetime": "2024-04-08T12:00:00+00:00",
        "netFlow": -16.0,
        "sortedZoneKeys": "GE->RU-1",
        "source": "gse.com.ge",
        "sourceType": "measured",
    }
]

snapshots["test_fetch_exchange_live[TR] 1"] = [
    {
        "datetime": "2024-04-08T12:00:00+00:00",
        "netFlow": 0.0,
        "sortedZoneKeys": "GE->TR",
        "source": "gse.com.ge",
        "sourceType": "measured",
    }
]

snapshots["test_fetch_production_historical 1"] = [
    {
        "correctedModes": [],
        "datetime": "2020-01-01T00:00:00+00:00",
        "production": {"gas": 619, "hydro": 348, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T01:00:00+00:00",
        "production": {"gas": 619, "hydro": 323, "solar": 0, "wind": 15},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T02:00:00+00:00",
        "production": {"gas": 619, "hydro": 321, "solar": 0, "wind": 7},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T03:00:00+00:00",
        "production": {"gas": 619, "hydro": 333, "solar": 0, "wind": 7},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T04:00:00+00:00",
        "production": {"gas": 618, "hydro": 339, "solar": 0, "wind": 7},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T05:00:00+00:00",
        "production": {"gas": 618, "hydro": 381, "solar": 0, "wind": 5},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T06:00:00+00:00",
        "production": {"gas": 615, "hydro": 482, "solar": 0, "wind": 2},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T07:00:00+00:00",
        "production": {"gas": 611, "hydro": 551, "solar": 0, "wind": 3},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T08:00:00+00:00",
        "production": {"gas": 608, "hydro": 567, "solar": 0, "wind": 8},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T09:00:00+00:00",
        "production": {"gas": 604, "hydro": 577, "solar": 0, "wind": 9},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T10:00:00+00:00",
        "production": {"gas": 604, "hydro": 569, "solar": 0, "wind": 14},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T11:00:00+00:00",
        "production": {"gas": 605, "hydro": 561, "solar": 0, "wind": 17},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T12:00:00+00:00",
        "production": {"gas": 604, "hydro": 562, "solar": 0, "wind": 18},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T13:00:00+00:00",
        "production": {"gas": 606, "hydro": 597, "solar": 0, "wind": 21},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T14:00:00+00:00",
        "production": {"gas": 607, "hydro": 700, "solar": 0, "wind": 21},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T15:00:00+00:00",
        "production": {"gas": 607, "hydro": 718, "solar": 0, "wind": 21},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T16:00:00+00:00",
        "production": {"gas": 606, "hydro": 701, "solar": 0, "wind": 21},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T17:00:00+00:00",
        "production": {"gas": 610, "hydro": 681, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T18:00:00+00:00",
        "production": {"gas": 608, "hydro": 662, "solar": 0, "wind": 18},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T19:00:00+00:00",
        "production": {"gas": 608, "hydro": 585, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T20:00:00+00:00",
        "production": {"gas": 611, "hydro": 505, "solar": 0, "wind": 21},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T21:00:00+00:00",
        "production": {"gas": 613, "hydro": 406, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T22:00:00+00:00",
        "production": {"gas": 614, "hydro": 371, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2020-01-01T23:00:00+00:00",
        "production": {"gas": 616, "hydro": 387, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
]

snapshots["test_fetch_production_live 1"] = [
    {
        "correctedModes": [],
        "datetime": "2024-04-09T00:00:00+00:00",
        "production": {"gas": 251, "hydro": 1078, "solar": 0, "wind": 17},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T01:00:00+00:00",
        "production": {"gas": 251, "hydro": 1068, "solar": 0, "wind": 15},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T02:00:00+00:00",
        "production": {"gas": 251, "hydro": 1115, "solar": 0, "wind": 13},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T03:00:00+00:00",
        "production": {"gas": 247, "hydro": 972, "solar": 0, "wind": 13},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T04:00:00+00:00",
        "production": {"gas": 244, "hydro": 1050, "solar": 0, "wind": 16},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T05:00:00+00:00",
        "production": {"gas": 243, "hydro": 1141, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T06:00:00+00:00",
        "production": {"gas": 254, "hydro": 1226, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T07:00:00+00:00",
        "production": {"gas": 310, "hydro": 1271, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T08:00:00+00:00",
        "production": {"gas": 322, "hydro": 1268, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T09:00:00+00:00",
        "production": {"gas": 306, "hydro": 1240, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T10:00:00+00:00",
        "production": {"gas": 272, "hydro": 1253, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T11:00:00+00:00",
        "production": {"gas": 272, "hydro": 1266, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T12:00:00+00:00",
        "production": {"gas": 273, "hydro": 1235, "solar": 0, "wind": 20},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T13:00:00+00:00",
        "production": {"gas": 256, "hydro": 1210, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T14:00:00+00:00",
        "production": {"gas": 244, "hydro": 1231, "solar": 0, "wind": 16},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
    {
        "correctedModes": [],
        "datetime": "2024-04-09T15:00:00+00:00",
        "production": {"gas": 271, "hydro": 1296, "solar": 0, "wind": 19},
        "source": "gse.com.ge",
        "sourceType": "measured",
        "storage": {},
        "zoneKey": "GE",
    },
]
