VERSION 0.8
FROM alpine:latest
WORKDIR /contrib/config


src-files:
  COPY . .
  SAVE ARTIFACT .

data-centers-files:
  COPY data_centers/data_centers.json ./data_centers/data_centers.json
  SAVE ARTIFACT .

test:
  RUN echo "tests should live here"