bounding_box:
  - - -6.988389900229108
    - 61.39207339559458
  - - -6.668657472558352
    - 61.6530567252827
capacity:
  hydro: 3.3
  oil: 13.6
  solar: 0.24
  wind: 6
center_point:
  - -6.82852368639373
  - 61.52256506043864
centroid:
  - -6.8038229048162115
  - 61.530854520581684
contributors:
  - corradio
  - q--
  - VIKTORVAV99
  - amv213
country: FO
country_name: Faroe Islands
currency: DKK
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0
    coal:
      - datetime: '2017-01-01'
        source: EU-ETS 2025, ENTSO-E 2017
        value: 1061.07
      - datetime: '2018-01-01'
        source: EU-ETS 2025, ENTSO-E 2018
        value: 1027.14
      - datetime: '2019-01-01'
        source: EU-ETS 2025, ENTSO-E 2019
        value: 1044.66
      - datetime: '2020-01-01'
        source: EU-ETS 2025, ENTSO-E 2020
        value: 1033.67
      - datetime: '2021-01-01'
        source: EU-ETS 2025, ENTSO-E 2021
        value: 1032.94
      - datetime: '2022-01-01'
        source: EU-ETS 2025, ENTSO-E 2022
        value: 1039.0
      - datetime: '2023-01-01'
        source: EU-ETS 2025, ENTSO-E 2023
        value: 1041.95
      - datetime: '2024-01-01'
        source: EU-ETS 2025, ENTSO-E 2024
        value: 1048.95
      - datetime: '2025-01-01'
        source: EU-ETS 2025, ENTSO-E 2025
        value: 1035.2
    gas:
      - datetime: '2017-01-01'
        source: EU-ETS 2025, ENTSO-E 2017
        value: 391.05
      - datetime: '2018-01-01'
        source: EU-ETS 2025, ENTSO-E 2018
        value: 395.08
      - datetime: '2019-01-01'
        source: EU-ETS 2025, ENTSO-E 2019
        value: 382.65
      - datetime: '2020-01-01'
        source: EU-ETS 2025, ENTSO-E 2020
        value: 387.04
      - datetime: '2021-01-01'
        source: EU-ETS 2025, ENTSO-E 2021
        value: 386.78
      - datetime: '2022-01-01'
        source: EU-ETS 2025, ENTSO-E 2022
        value: 394.63
      - datetime: '2023-01-01'
        source: EU-ETS 2025, ENTSO-E 2023
        value: 399.0
      - datetime: '2024-01-01'
        source: EU-ETS 2025, ENTSO-E 2024
        value: 396.31
      - datetime: '2025-01-01'
        source: EU-ETS 2025, ENTSO-E 2025
        value: 389.72
    oil:
      - datetime: '2017-01-01'
        source: EU-ETS 2025, ENTSO-E 2017
        value: 910.01
      - datetime: '2018-01-01'
        source: EU-ETS 2025, ENTSO-E 2018
        value: 957.57
      - datetime: '2019-01-01'
        source: EU-ETS 2025, ENTSO-E 2019
        value: 972.1
      - datetime: '2020-01-01'
        source: EU-ETS 2025, ENTSO-E 2020
        value: 967.1
      - datetime: '2021-01-01'
        source: EU-ETS 2025, ENTSO-E 2021
        value: 903.53
      - datetime: '2022-01-01'
        source: EU-ETS 2025, ENTSO-E 2022
        value: 873.76
      - datetime: '2023-01-01'
        source: EU-ETS 2025, ENTSO-E 2023
        value: 850.74
      - datetime: '2024-01-01'
        source: EU-ETS 2025, ENTSO-E 2024
        value: 869.31
      - datetime: '2025-01-01'
        source: EU-ETS 2025, ENTSO-E 2025
        value: 826.11
    unknown:
      comment: Data reflects median Ocean (tidal) lifecycle emissions from table A.III.2
      source: IPCC 2014
      value: 0
  lifecycle:
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230
    coal:
      - datetime: '2017-01-01'
        source: EU-ETS 2025, ENTSO-E 2017; IPCC 2014
        value: 1121.07
      - datetime: '2018-01-01'
        source: EU-ETS 2025, ENTSO-E 2018; IPCC 2014
        value: 1087.14
      - datetime: '2019-01-01'
        source: EU-ETS 2025, ENTSO-E 2019; IPCC 2014
        value: 1104.66
      - datetime: '2020-01-01'
        source: EU-ETS 2025, ENTSO-E 2020; IPCC 2014
        value: 1093.67
      - datetime: '2021-01-01'
        source: EU-ETS 2025, ENTSO-E 2021; IPCC 2014
        value: 1092.94
      - datetime: '2022-01-01'
        source: EU-ETS 2025, ENTSO-E 2022; IPCC 2014
        value: 1099.0
      - datetime: '2023-01-01'
        source: EU-ETS 2025, ENTSO-E 2023; IPCC 2014
        value: 1101.95
      - datetime: '2024-01-01'
        source: EU-ETS 2025, ENTSO-E 2024; IPCC 2014
        value: 1108.95
      - datetime: '2025-01-01'
        source: EU-ETS 2025, ENTSO-E 2025; IPCC 2014
        value: 1095.2
    gas:
      - datetime: '2017-01-01'
        source: EU-ETS 2025, ENTSO-E 2017; IPCC 2014
        value: 511.05
      - datetime: '2018-01-01'
        source: EU-ETS 2025, ENTSO-E 2018; IPCC 2014
        value: 515.08
      - datetime: '2019-01-01'
        source: EU-ETS 2025, ENTSO-E 2019; IPCC 2014
        value: 502.65
      - datetime: '2020-01-01'
        source: EU-ETS 2025, ENTSO-E 2020; IPCC 2014
        value: 507.04
      - datetime: '2021-01-01'
        source: EU-ETS 2025, ENTSO-E 2021; IPCC 2014
        value: 506.78
      - datetime: '2022-01-01'
        source: EU-ETS 2025, ENTSO-E 2022; IPCC 2014
        value: 514.63
      - datetime: '2023-01-01'
        source: EU-ETS 2025, ENTSO-E 2023; IPCC 2014
        value: 519.0
      - datetime: '2024-01-01'
        source: EU-ETS 2025, ENTSO-E 2024; IPCC 2014
        value: 516.31
      - datetime: '2025-01-01'
        source: EU-ETS 2025, ENTSO-E 2025; IPCC 2014
        value: 509.72
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2017-01-01'
        source: EU-ETS 2025, ENTSO-E 2017; IPCC 2014
        value: 1154.01
      - datetime: '2018-01-01'
        source: EU-ETS 2025, ENTSO-E 2018; IPCC 2014
        value: 1201.57
      - datetime: '2019-01-01'
        source: EU-ETS 2025, ENTSO-E 2019; IPCC 2014
        value: 1216.1
      - datetime: '2020-01-01'
        source: EU-ETS 2025, ENTSO-E 2020; IPCC 2014
        value: 1211.1
      - datetime: '2021-01-01'
        source: EU-ETS 2025, ENTSO-E 2021; IPCC 2014
        value: 1147.53
      - datetime: '2022-01-01'
        source: EU-ETS 2025, ENTSO-E 2022; IPCC 2014
        value: 1117.76
      - datetime: '2023-01-01'
        source: EU-ETS 2025, ENTSO-E 2023; IPCC 2014
        value: 1094.74
      - datetime: '2024-01-01'
        source: EU-ETS 2025, ENTSO-E 2024; IPCC 2014
        value: 1113.31
      - datetime: '2025-01-01'
        source: EU-ETS 2025, ENTSO-E 2025; IPCC 2014
        value: 1070.11
    unknown:
      comment: Data reflects median Ocean (tidal) lifecycle emissions from table A.III.2
      source: IPCC 2014
      value: 17
    wind:
      datetime: '2014-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.132198084846763
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.5297837798007383
        solar: 0.0045826520006905765
        unknown: 0.0
        wind: 0.3334277688972878
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.11800670796717387
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.4408138238297388
        solar: 0.005933823038562434
        unknown: 0.0
        wind: 0.43524042559796317
    - _source: Electricity Maps, 2024 average
      datetime: '2024-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.050524812072244754
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.46860447661480964
        solar: 0.004961919576653245
        unknown: 0.0
        wind: 0.475904117942365
has_day_ahead_price_license: false
hide_day_ahead_price: false
isLowCarbon:
  unknown:
    value: 1
isRenewable:
  unknown:
    value: 1
parsers:
  production: FO.fetch_production
region: Europe
sources:
  EU-ETS 2025, ENTSO-E 2017:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2018:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2019:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2020:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2021:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2022:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2023:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2024:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS 2025, ENTSO-E 2025:
    link: https://transparency.entsoe.eu/, https://climate.ec.europa.eu/eu-action/carbon-markets/union-registry_en
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  EU-ETS, ENTSO-E 2024:
    link: https://transparency.entsoe.eu/
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Atlantic/Faroe
zone_name: South Island
